# Site settings
title: Erin Bergman
description: 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site

# User settings
username: Erin Bergman
user_title: Electrical Engineer
email: emb0020@uah.edu
github_username:  ErinBergman
linkedin_username: erin-bergman-042b78130

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
